let x = "Hello";
let y = "World<br>";
let z = x + y;
document.write(z);
let n = x + " " + y;
x += n;
document.write(x);
let meinString = "Ich bin Erster";
meinString += " Ich komme auf Platz zwei";
document.write(meinString);